name: Edmonton Wedding Photographer
favicon: null
layout_spectrum: 0.2547
typography_spectrum: 0.50118
title: Instant Memories Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08080b'
    - '#eaf1fb'
    - '#a0b8e4'
    - '#6685be'
    - '#f1d23a'
  brandStrength: 0.5
  lightness: 0.051084715174511075
  saturation: 0.375
  rhythmicContrast: 0.7841874191071838
purpose: []
